### ISSUE TITLE
Login username is case-sensitive

### ISSUE THREAD

**Issue by robere2** [rpitv/glimpse#67]
If a username in the database is `robere2` but they try to log in as `Robere2`, it will fail. Make sure that you don't just perform a case-insensitive check on login, but on account registration as well (if that does not already exist).

**Comment by evnxprk** [comment]
Just to clarify, you want the username to be case-sensitive? So in this case, if they signed up with robere2, it HAS to be robere2 and not Robere2.

**Comment by robere2** [comment]
Correct! Or perhaps more accurately, all usernames should be required to be lowercase, so any time a username inputs should also be converted to lowercase.

If you're interested in tackling this issue, I believe you're going to want to update the [GraphQL resolvers for `createUser` and `updateUser` ](https://github.com/rpitv/glimpse/blob/master/apps/api/src/types/user/user.resolver.ts)to modify `input.username` to be lowercase.

Update username to be lowercase in [`attemptLogin` as well in `auth.service.ts`.](https://github.com/rpitv/glimpse/blob/master/apps/api/src/auth/auth.service.ts#L30)

There's no way for new users to make their own accounts right now, so you don't need to worry about that.

**Comment by robere2** [comment]
There may be additional locations in the code where this will need to be fixed, such as search filters, but I haven't tested this and this may be a more complex issue that deserves its own lower-priority issue.

**Comment by evnxprk** [comment]
Okay so would you prefer me just to work on the lowercase and just that? If so, I can work on this but there might be a few trial and errors because I have not worked with GraphQL.
